<a href="https://colab.research.google.com/github/Israamanaziz/Python-for-absolute-beginners/blob/main/Python_basics_ML.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Programming languages used for ML
1. Python
2. R

In [ ]:
#print function
print("ML")

ML


In [ ]:
print("ML "+ " Project")

ML  Project


In [ ]:
print(8)

8


In [ ]:
print(8+8)

16


#Basic data types
1.integer

2.floating point

3.string

4.Boolean

5.Complex



In [ ]:
# integers
a=8
print(a)
type(a)

# floating point

b = 2.3
print(b)
type(b)

8
2.3


float

In [ ]:
#convert int to float
x = 5
print(x)
type(x)

5


int

In [ ]:
y = float(x)
print(y)
type(y)

5.0


float

In [ ]:
# boolean
a = 7>3
print (a)
type(a)

True


bool

In [ ]:
#String
print("Hello"*3)

HelloHelloHello


In [ ]:
#SLICING
my_string = "Machine Learning"
print(my_string[1:4])
print(my_string[:4])
print(my_string[9:])

#Step
print(my_string[0:10:3])

ach
Mach
earning
Mhee


###STRING CONCATENATION


In [ ]:
word_1 = "Isra"
word_2 = "Aman"
print(word_1 + ' '  +  word_2)

Isra Aman


#Constants & Variables


In [ ]:
 superman = "Iron man"
print("superman")

superman


# INPUT FUNCTION

In [ ]:
number_1 = int(input("Enter the first num:"))
number_2 = int(input("Enter the second num:"))

sum = number_1 + number_2
print(sum)

Enter the first num:2
Enter the second num:4
6


In [ ]:
 # Changing the datatype in python
 num = 5
 print(float(num))

5.0


#Types of Objects in Python

1. Immutable Objects
2. Mutable Objects

IMMUTABLE:
1. int
2. float
3. string
4. bool
5. tuple

Mutable
1. List
2. Set
3. Dictionary

In [ ]:
# List : Square Bracket [] arrays in program, store multiple values
 my_list = [1,2,3,3,4,5,6,7,4,8,]
 print(my_list)
 type(my_list)


[1, 2, 3, 3, 4, 5, 6, 7, 4, 8]


list

In [ ]:
 # list can have multiple data types, allows duplicate values
 my_list2 = [2,3, 4.5, "Maths, true"]
 print(my_list2)
 type(my_list2)

[2, 3, 4.5, 'Maths, true']


list

In [ ]:
#Add elements to list (List are mutable)
 my_list2 = [2,3, 4.5, "Maths", True]
 my_list2.append(9)
 print(my_list2)

[2, 3, 4.5, 'Maths', True, 9]


In [ ]:
# we can delete list elements
my_list2 = [2,3, 4.5, "Maths", True]
print(my_list2)

del my_list2[2]
print(my_list2)

[2, 3, 4.5, 'Maths', True]
[2, 3, 'Maths', True]


In [ ]:
# add 2 lists
list_3 = [3,4,5,6,9]
list_4 = [1,2,3,4]
list_5 = list_3 + list_4
print(list_5)

[3, 4, 5, 6, 9, 1, 2, 3, 4]


TUPLE

In [ ]:
tuple_1 = (1,2,3,4)
print(tuple_1)
# allows multiple data types
# tuple are immutable(unchhangeable), so no append or anything
# converting a list to tuple
my_list7 = [2,3,4,5,6,7]
print(my_list7)

tuple4 = tuple(my_list7)
print(tuple4)

(1, 2, 3, 4)
[2, 3, 4, 5, 6, 7]
(2, 3, 4, 5, 6, 7)


Dictionary

In [ ]:
#dictionary has a key and value
#does not allow duplicate values
dict1 = {'name': 'David', 'age':'34','Country': 'India'}
print(dict1)
type(dict1)
print(dict1['name'])
print(dict1['age'])
print(dict1['Country'])

{'name': 'David', 'age': '34', 'Country': 'India'}
David
34
India


Operators in Python

1.Arithmetic

2.Assignment

3.Comparison

4.Logical

5.Identity

6.Memebership

In [ ]:
n=1
h=3
sum = n + h
print('sum =',sum)

diff = n - h
print('diff =', diff)


sum = 4
diff = -2


# IF-ELSE Statement

In [ ]:
a = 10
b = 60

if(a>b):
  print('a is the greatest number')
else:
    print('B is the greatest number')

B is th egreatest number


In [ ]:
a = int(input('Enter the first number:'))
b = int(input('Enter the second number:'))

if (a >b):
  print('a is the greatest number')
else:
  print('b is the greatest number')

Enter the first number:34476
Enter the second number:873678
b is the greatest number


If-elif-else staement

In [ ]:
a = 34
b = 45
c = 56

if (a>b<c):
  print('a is the greatest no')
elif (a<b<c):
  print(' b is the greatest statement')
else:
  print('c is the greatest no')

 b is the greatest statement


nested if else

In [ ]:
a = 34
b = 45
c = 56

if (a<b):
  if(a<c):
    print('a is the smallest number')
  else:
    print('c is the smallest number')
else:
    if(b<c):
      print('b is the smallest number')
    else:
      print('c is the smallest number')

a is the smallest number


# LOOPS IN PYTHON
FOR LOOPS

WHILE LOOPS

DO WHILE LOOPS

In [ ]:
laptop1 = int(input('Enter the price of the laptop:'))

Enter the price of the laptop:340000


In [ ]:
for i in range(5): # 0,1,2,3,4
  laptop_price = int(input('Enter the price of the laptop: '))

Enter the price of the laptop: 34000
Enter the price of the laptop: 34000
Enter the price of the laptop: 76776
Enter the price of the laptop: 7567
Enter the price of the laptop: 65675


In [ ]:
numbers = [50,100,150,200,300]

print(numbers[0])
print(numbers[1])
print(numbers[2])
print(numbers[3])

50
100
150
200


In [ ]:
numbers = [50,100,150,200,300]

for i in numbers:
  print(i)

50
100
150
200
300


**While Loop is used when we do not know the number of times an action has to be executed**

In [ ]:
i = 0

while i<10:
  print(i)
  i +=1

0
1
2
3
4
5
6
7
8
9


In [ ]:
i = 5

while i < 5:
  print(i)
  i += 1

# FUNCTIONS IN PYTHON

Function is a block of code that can be reused in a program

In [ ]:
# Factorial of a number 5 = 5*4*3*2*1

number = int(input('Enter the given number: '))

fact = 1

if number == 0:
  print('The factorial of 0 is 1')

else:
  for i in range(1, num +1):
    fact = fact*i
  print('The factorial of', number, 'is', fact)

Enter the given number: 5
The factorial of 5 is 120


FACTORIAL FUNCTION

In [ ]:
def Factorial_value(num):
  fact = 1
  if num == 0:
    return fact

  else:
   for i in range(1, num +1):
    fact = fact*i
   return fact

In [ ]:
print(Factorial_value(5))

120


In [ ]:
print(Factorial_value(10))

3628800


# NumPy - Numerical Python

1.Allows several Mathematical Operations

2.faster Operations

In [ ]:
import numpy as np

List vs NumPy time taken

In [ ]:
from time import process_time

In [ ]:
# Time taken by a list
python_list = [i for i in range(10000)]

start_time = process_time()

python_list = [i + 5 for i in python_list]

end_time = process_time()

print(end_time - start_time)

0.0007158519999990176


In [ ]:
# Time taken by Numpy array

np_array = np.array([i for i in range(10000)])

start_time = process_time()

np_array += 5

end_time = process_time()

print(end_time - start_time)

0.0002378859999936367


In [ ]:
# creating a list
list1 = [1,2,3,4]
print(list1)
type(list1)

[1, 2, 3, 4]


list

In [ ]:
# Creating a 1 dimensional array
x = np.array([1,2,3,4])
print(x)

[1 2 3 4]


In [ ]:
x.shape

(4,)

In [ ]:
# create a 2 dimensional array
b = np.array([(1,2,3,4), (5,6,7,8),(9,10,11,12)])
print(b)


b.shape
# 1st rows, 2nd columns

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


(3, 4)

In [ ]:
c = np.array([(1,2,3,4,5)], dtype=float)
print(c)

[[1. 2. 3. 4. 5.]]


In [ ]:
# Initialising placeholders iin numpy arrays


# Create a numpy array of Zeros

x = np.zeros((4,5))
print(x)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [ ]:
#create numpy array of ones

y = np.ones((4,6))
print(y)

[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]


In [ ]:
# creating numpy array of a particular value

z = np.full((3,4),7)
print(z)

[[7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]]


In [ ]:
# Create an Identity Matrix
a = np.eye(6)
print(a)

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]


In [ ]:
# Create a numpy array with random values
b = np.random.random((4,5))
print(b)

[[0.40284802 0.95434853 0.03459171 0.52573485 0.69911826]
 [0.83179353 0.99344464 0.7213077  0.01948463 0.52068884]
 [0.28301074 0.37972678 0.08345203 0.53577424 0.62753716]
 [0.1041909  0.04524097 0.37680704 0.09068858 0.8808527 ]]


In [ ]:
# random integer value array within a specific range

c = np.random.randint(10,100,(3,6))  # 10-100 range, 3-6 column
print(c)

[[32 74 10 87 42 44]
 [94 93 27 62 36 55]
 [22 25 40 86 61 54]]


In [ ]:
# array of evenly spaced values

d = np.linspace(10,100,5)
print(d)

[ 10.   32.5  55.   77.5 100. ]


In [ ]:
# convert a list into numpy array

list2 = [2,3,4,5,6,7]

np_array = np.asarray(list2)
print(np_array)

[2 3 4 5 6 7]


In [ ]:
# Analysing a particular array

t = np.random.randint(10,90,(5,5))

print(t)


#

[[28 44 45 10 87]
 [57 54 41 22 23]
 [55 17 44 26 57]
 [74 76 82 12 78]
 [64 49 39 19 80]]
